![title](https://image.ibb.co/erDntK/logo2018.png)

---


# Python NumPy exercise 2019
In this assignment you will practice the use of Python Programming Language

Complete the following tasks according to the expected ouputs

---
### 1. 
**Write your Student ID as string, then print the last four digit of your ID**
    <pre>`(2 lines ★☆☆)`

In [0]:
ID = '1301160098'

print('ID           :', ID)
print('last 4 digit :', ID[-4:])

ID           : 1301160098
last 4 digit : 0098


**Expected Output**:<pre>
<i>(assumed ID='1234567890')</i>

ID           : 1234567890
last 4 digit : 7890

---
### 2. 
**Import the numpy package under the name `np`, then print its version**
<pre>(2 lines ★☆☆) 

In [0]:
import numpy as np
np.version.version

'1.16.4'

**Expected Output**:<pre>
'1.1x.x'

---
### 3. 
**Create a null (all-zero) matrix of size $4\ \times\ 5$**
<pre>(1 line ★☆☆)

In [0]:
A = np.zeros((4,5))
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**Expected Output**:<pre>
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


---
### 4. 
**Set the third row values of matrix A to be `all 1`**
<pre>(2 lines ★☆☆)

In [0]:
A[2,:] = 1
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


**Expected Output**:<pre>
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]

---
### 5. 
**Create a random matrix with normal distribution of size $3\ \times\ 4$, using seed value = `123`**
<pre>(2 lines ★☆☆)

In [0]:
np.random.seed(123)
B = np.random.normal(0.0,1.0,(3,4))
print(B)

[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]]


**Expected Output**:<pre>
[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]]

---
### 6. 
**print the size of matrix B, then print matrix B with only `2 significant digits`**
<pre>(2 lines ★☆☆)

In [0]:
np.around(B,decimals=2)
print('size B =', B.shape)
print(B)

size B = (3, 4)
[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]]


**Expected Output**:<pre>
size B = (3, 4)
[[-1.09  1.    0.28 -1.51]
 [-0.58  1.65 -2.43 -0.43]
 [ 1.27 -0.87 -0.68 -0.09]]


---
### 7
**create a vector with values raging from `15 to 35`**
<pre>(1 line ★☆☆)

In [0]:
C = np.arange(15,36)
print(C)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


**Expected Output**:
<pre>[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]

---
### 8.  
**Reverse vector C (first element becomes last)**<pre> (1 line ★☆☆) 

In [0]:
D = np.flip(C)
print(C)
print(D)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
[35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15]


**Expected Output**:<pre>
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
[35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15]



---
### 9. 
**Create a $4\ \times\ 3$ matrix with values ranging from 0 to 11**<pre> (1 line ★☆☆) 


In [0]:
E = np.arange(12).reshape(4,3)
print(E)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


**Expected Output**:<pre>
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

---
### 10. 
**Find the indices of non-zero elements from the given matrix**<pre> (1 line ★☆☆) 

In [0]:
F = [1,2,0,0,4,0,0,7]
idF = np.nonzero(F)
print(idF[0])

[0 1 4 7]


**Expected Output**:<pre>[0 1 4 7]

---
### 11.
**Create a $4\ \times\ 4$ identity matrix**<pre> (1 line ★☆☆) 

In [0]:
G = np.identity(4)
print(G)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Expected Output**:<pre>[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

---
### 12. 
**Create a $3\ \times\ 2\ \times\ 3$ array of random values with uniform distribution and seed value = 123**<pre> (2 lines ★☆☆) 

In [0]:
np.random.seed(123)
H = np.around(np.random.uniform(0.0,1.0,(3,2,3)),decimals=2)
print(H)

[[[0.7  0.29 0.23]
  [0.55 0.72 0.42]]

 [[0.98 0.68 0.48]
  [0.39 0.34 0.73]]

 [[0.44 0.06 0.4 ]
  [0.74 0.18 0.18]]]


**Expected Output**:
<pre>
[[[0.7  0.29 0.23]
  [0.55 0.72 0.42]]

 [[0.98 0.68 0.48]
  [0.39 0.34 0.73]]

 [[0.44 0.06 0.4 ]
  [0.74 0.18 0.18]]]

---
### 13.
**Find the minimum and maximum values of matrix (H)**<pre> (2 lines ★☆☆) 

In [0]:
Hmin = np.amin(H)
Hmax = np.amax(H)
print(Hmin, Hmax)

0.06 0.98


**Expected Output**:<pre>0.05967789660956835 0.9807641983846155


---
### 14. 
**Create a random vector of size 50 and find the mean value**<pre> (2 lines ★☆☆) 

In [0]:
np.random.seed(123)
I = np.random.rand(50)
mI = np.mean(I)
print(mI)

0.5018578670875471


**Expected Output**:<pre>0.5018578670875471



---
### 15. 
**Create a $5 \times 5 $ array with all values = 1** <pre>(1 line ★☆☆) 

In [0]:
J = np.ones((5,5))
print(J)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Expected Output**:<pre>[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

---
### 16. 
**Set matrix J so that the value in `3rd to 4th` row, from `2nd to 4th` column, are all 0** <pre>(1 line ★☆☆) 

In [0]:
J[2:4,1:4] = 0
print(J)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Expected Output**:<pre>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

---
### 17. 
**Create a $4\ \times\ 4$ Random Integer matrix in range `[0..9]`, then add a zero padding border (filled with 0's) around it**<pre> (2 lines ★★☆) 

In [0]:
np.random.seed(12)
K = np.random.randint(9, size=(4,4))
K = np.pad(K, (1,1), 'constant')
print(K)

[[0 0 0 0 0 0]
 [0 6 1 2 3 0]
 [0 3 0 6 1 0]
 [0 4 5 2 6 0]
 [0 0 5 8 2 0]
 [0 0 0 0 0 0]]


**Expected Output**:<pre>
[[0 0 0 0 0 0]
 [0 6 1 2 3 0]
 [0 3 0 6 1 0]
 [0 4 5 2 6 0]
 [0 0 5 8 2 0]
 [0 0 0 0 0 0]]


---
### 18. 
**Create a $6\ \times\ 6$ matrix with values `0,1,2,3,4,5` on the diagonal** <pre>(1 line ★☆☆) 

In [0]:
L = np.diag(np.arange(6))
print(L)

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


**Expected Output**:<pre>[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


---
### 19. 
**Create a $7\ \times\ 7$ matrix with values `1,2,3,4,5,6` just `BELOW` the diagonal** <pre>(1 line ★☆☆) 

In [0]:
M = np.diag(np.arange(1,7),k=-1)
print(M)

[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]]


**Expected Output**:<pre>[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]]


---
### 20. 
**Create a $6\ \times\ 6$ matrix and fill it with a checkerboard pattern `WITHOUT` helper function** <pre>(3 lines ★★☆) 

In [0]:
N = np.zeros((6,6), dtype=int)  # use dtype=int
N[1::2,::2] = 1
N[::2,1::2] = 1
print(N)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


**Expected Output**:<pre>[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


---
### 21. 
**Create a checkerboard $6\ \times\ 6$ matrix using the `tile` function**<pre> (1 line ★☆☆)

In [0]:
O = np.tile(np.array([[0,1],[1,0]]), (3,3))
print(O)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


**Expected Output**:<pre>[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


---
### 22. 
**Create a $3\ \times\ 4$ random uniform matrix, then normalize the values to range [0-1]**<pre> (2 lines ★★☆) 

In [0]:
np.random.seed(25)
P = np.around(np.random.uniform(0.0,1.0,(3,2)),decimals=2)
print('before')
print(P,'\n')

Pmax, Pmin = P.max(), P.min()
P = np.around((P-Pmin)/(Pmax-Pmin),decimals=2)
print('after')
print(P)

before
[[0.87 0.58]
 [0.28 0.19]
 [0.41 0.12]] 

after
[[1.   0.61]
 [0.21 0.09]
 [0.39 0.  ]]


**Expected Output**:<pre>before
[[0.87 0.58]
 [0.28 0.19]
 [0.41 0.12]] 
<br>after
[[1.   0.62]
 [0.21 0.09]
 [0.39 0.  ]]



---
### 23. 
**Multiply matrix `E` by matrix `P` (dot product)**<pre> (1 line ★☆☆)

In [0]:
Q = np.dot(E,P)
print(Q)

[[ 0.99  0.09]
 [ 5.79  2.19]
 [10.59  4.29]
 [15.39  6.39]]


**Expected Output**:<pre>[[ 0.99  0.09]
 [ 5.81  2.22]
 [10.62  4.34]
 [15.44  6.47]]


---
### 24. 
**Given a 1D array, negate all elements which are `between -4 and 3`, in place.**<pre> (1 line ★☆☆)

In [0]:
R = np.arange(-8,9)
print('before')
print(R,'\n')

R = np.negative(R,where=np.logical_and(R>=-4,R<=3))
print('after')
print(R)

before
[-8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8] 

after
[           44676752 1840251303768347936     140063262841200
     140063262841200                   4                   3
                   2                   1                   0
                  -1                  -2                  -3
     140063262841392 2698739288317414779     140063262855576
     140063262855576 6289678934905434693]


**Expected Output**:<pre>before
[-8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8] 
<br>after
[-8 -7 -6 -5 -4  3  2  1  0 -1 -2  3  4  5  6  7  8]

---
### 25. 
**Get common values between two given arrays**<pre> (1 line ★☆☆) 

In [0]:
np.random.seed(3)
S1 = np.random.randint(0,10,10)
print('S1=', S1,'\n')

np.random.seed(5)
S2 = np.random.randint(0,10,10)
print('S2=', S2,'\n')

S = np.intersect1d(S1,S2)
print('S =', S)

S1= [8 9 3 8 8 0 5 3 9 9] 

S2= [3 6 6 0 9 8 4 7 0 0] 

S = [0 3 8 9]


**Expected Output**:<pre>S1= [8 9 3 8 8 0 5 3 9 9] 
<br>S2= [3 6 6 0 9 8 4 7 0 0] 
<br>S = [0 3 8 9]


---
### 26 
**Create random uniform vector of `size 12` then replace the maximum value by `1`, and replace the minimum value by `0`**<pre>( 3 lines ★★☆) 

In [0]:
np.random.seed(15)
T = np.around(np.random.uniform(0.0,1.0,12),decimals=2)
print('before=',T,'\n')

T[T.argmax()] = 1
T[T.argmin()] = 0
print('after =',T)

before= [0.85 0.18 0.05 0.36 0.28 0.53 0.31 0.3  0.11 0.25 0.92 0.26] 

after = [0.85 0.18 0.   0.36 0.28 0.53 0.31 0.3  0.11 0.25 1.   0.26]


**Expected Output**:<pre>before= [0.85 0.18 0.05 0.36 0.28 0.53 0.31 0.3  0.11 0.25 0.92 0.26] 
<br>after = [0.85 0.18 0.   0.36 0.28 0.53 0.31 0.3  0.11 0.25 1.   0.26]

---
### 27. 
**Get the `MEAN` of matrix `Q`, also `mean value across the row and column`**<pre> (2 line ★★☆)</pre>
hint: use `axis ` and `keepdims`

In [0]:
print('Q')
print(Q,'\n')
U1 = np.mean(Q)
U2 = np.mean(Q, axis=1)
U3 = np.mean(Q, axis=0)

print('Matrix Mean')
print(U1,'\n')

print('Row Mean')
print(U2,'\n')

print('Column Mean')
print(U3)

Q
[[ 0.99  0.09]
 [ 5.79  2.19]
 [10.59  4.29]
 [15.39  6.39]] 

Matrix Mean
5.715 

Row Mean
[ 0.54  3.99  7.44 10.89] 

Column Mean
[8.19 3.24]


**Expected Output**:<pre>Q
[[ 0.99  0.09]
 [ 5.81  2.22]
 [10.62  4.34]
 [15.44  6.47]] 
<br>Matrix Mean
5.748021117169012 
<br>Row Mean
[[ 0.54]
 [ 4.01]
 [ 7.48]
 [10.95]] 
<br>Column Mean
[[8.22 3.28]]

---
### 28. 
**Swap 1st and 3rd row of given $5\ \times\ 5$ matrix**<pre>(1 line ★★☆) 

In [0]:
np.random.seed(21)
V = np.random.randint(1,10,(5,5))
print('before')
print(V,'\n')

V[[0,2]] = V[[2,0]]
print('after')
print(V)

before
[[9 5 1 1 9]
 [4 3 2 9 7]
 [1 5 7 5 5]
 [8 9 6 7 6]
 [3 7 3 9 3]] 

after
[[1 5 7 5 5]
 [4 3 2 9 7]
 [9 5 1 1 9]
 [8 9 6 7 6]
 [3 7 3 9 3]]


**Expected Output**:<pre>before
[[9 5 1 1 9]
 [4 3 2 9 7]
 [1 5 7 5 5]
 [8 9 6 7 6]
 [3 7 3 9 3]] 
<br>after
[[1 5 7 5 5]
 [4 3 2 9 7]
 [9 5 1 1 9]
 [8 9 6 7 6]
 [3 7 3 9 3]]

---
### 29. 
**Save all matrices `A to V` into a `.npz` file with your ID as the filename**

In [0]:
np.savez(ID+'.npz', A=A, B=B, C=C, D=D, E=E, F=F, G=G, H=H, I=I, J=J, K=K, L=L, M=M, N=N, O=O, P=P, Q=Q, R=R, S=S, T=T, U1=U1, U2=U2, U3=U3, V=V)

In [0]:
print(data['A'].shape)
print(data['Q'].shape)
print(data['V'].shape)

NameError: ignored

---
### 30.
**Clear all variables using `%reset`, then load your `.npz` file into `data` dictionary and verify the loaded matrices**

run this and press y to reset all variables

In [0]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


check loaded variables

In [0]:
import numpy as np
ID = '1301160098'
data = np.load(ID+'.npz')
print(data['A'].shape)
print(data['Q'].shape)
print(data['V'].shape)

(4, 5)
(4, 2)
(5, 5)


---

# Congratulation, You've Completed Pre-Exercise
<p>Copyright &copy;  <a href=https://www.linkedin.com/in/andityaarifianto/>2019 - ADF</a> </p>

![footer](https://image.ibb.co/hAHDYK/footer2018.png)